### PR TITLE
junk1

### PR DESCRIPTION
**Pull request by nmarley**

### CODE REVIEW

**Comment by nmarley** [comment]
@spencerlievens This is a junk commit for testing Travis-CI integration/Github branch protection.

**Comment by SCDeveloper** [comment]
Ha, thought as much. I have been following your work and using Sentinel for DarkSilk-Core. I had to do similar and added an * to the readme to simply trigger travis-ci on our github :D

**Comment by SCDeveloper** [comment]
https://github.com/silknetwork/darksilk-core (v1.0.0.0 branch)
https://github.com/silknetwork/darksilk-sentinel (master branch)
https://github.com/silknetwork/silk-core (master branch)

**Comment by SCDeveloper** [comment]
screen shot 2017-01-30 at 15 08 43

capture243

**Pull request closed without merging**
